"""Stage L: Auto-cut multiple Shorts teasers from the main video.

Generates 3-5 Shorts (~60sec each) with:
- 9:16 center crop for vertical 1080x1920
- Fresh, larger subtitles burnt for portrait readability (config: shorts.subtitle_font_size)
- Source = composed.mp4 (no subs) so we can re-burn at correct portrait size
- Quality encoding for YouTube Shorts

Each clip's SRT is generated by time-shifting the project's raw.srt to start at 0.
"""

from __future__ import annotations

import json
import re
import subprocess
from pathlib import Path

import yaml

from src.engines.llm_client import PROJECT_ROOT
from src.models import ProjectManifest, Scene, Script
from src.pipeline.base_stage import BaseStage


class ShortsTeaserStage(BaseStage):
    name = "l_shorts_teaser"
    dependencies = ["h_video_compose"]

    def execute(self, project_dir: Path, manifest: ProjectManifest) -> float:
        script = Script.model_validate_json(
            (project_dir / "script.json").read_text(encoding="utf-8")
        )

        with open(PROJECT_ROOT / "config" / "settings.yaml", encoding="utf-8") as f:
            settings = yaml.safe_load(f)

        shorts_cfg = settings.get("shorts", {})
        subtitle_cfg = settings.get("subtitle", {})

        target_duration = float(shorts_cfg.get("target_duration_sec", 60))
        min_duration = float(shorts_cfg.get("min_duration_sec", 45))
        max_duration = float(shorts_cfg.get("max_duration_sec", 70))
        font_size = int(shorts_cfg.get("subtitle_font_size", 64))
        margin_v = int(shorts_cfg.get("subtitle_margin_v", 240))
        font_name = subtitle_cfg.get("font", "NanumSquareRoundEB")
        source_name = shorts_cfg.get("source_video", "composed.mp4")

        # Pick source: prefer pre-subtitle composed.mp4 (clean), fall back to final.mp4
        candidate = project_dir / "video" / source_name
        if candidate.exists():
            source_video = candidate
            burn_fresh_subs = True
        else:
            source_video = project_dir / "video" / "final.mp4"
            burn_fresh_subs = False
            self.log.warning("composed_mp4_missing_falling_back_to_final_with_subs")

        if not source_video.exists():
            self.log.warning("source_video_missing", path=str(source_video))
            return 0.0

        source_duration = self._get_duration(source_video)
        if source_duration <= 0:
            self.log.warning("cannot_detect_video_duration")
            return 0.0

        srt_path = project_dir / "subtitles" / "raw.srt"
        clips = self._plan_shorts_clips(
            script,
            source_duration,
            target_duration,
            min_duration,
            max_duration,
            project_dir=project_dir,
        )
        created: list[dict] = []

        for i, clip in enumerate(clips):
            output_path = project_dir / "video" / f"shorts_{i + 1:02d}.mp4"

            # Per-short SRT (time-shifted) when we're re-burning subs
            short_srt: Path | None = None
            if burn_fresh_subs and srt_path.exists():
                short_srt = project_dir / "video" / f"shorts_{i + 1:02d}.srt"
                self._slice_srt(
                    src=srt_path,
                    dst=short_srt,
                    start_sec=clip["start"],
                    duration_sec=clip["duration"],
                )

            try:
                self._extract_short(
                    source=source_video,
                    output=output_path,
                    start_sec=clip["start"],
                    duration=clip["duration"],
                    source_duration=source_duration,
                    srt_path=short_srt,
                    font_name=font_name,
                    font_size=font_size,
                    margin_v=margin_v,
                )

                out_dur = self._get_duration(output_path)
                if out_dur > 1:
                    created.append({
                        "file": output_path.name,
                        "start": round(clip["start"], 1),
                        "duration": round(out_dur, 1),
                        "label": clip["label"],
                    })
                    self.log.info(
                        "short_created",
                        index=i + 1,
                        label=clip["label"],
                        duration=round(out_dur, 1),
                    )
                else:
                    output_path.unlink(missing_ok=True)
                    self.log.warning("short_too_short", index=i + 1)

            except subprocess.CalledProcessError as e:
                self.log.warning("short_failed", index=i + 1, error=str(e))
            finally:
                # Clean up per-short SRT after the burn
                if short_srt is not None and short_srt.exists():
                    short_srt.unlink(missing_ok=True)

        # Main teaser = first successful short
        if created:
            import shutil
            main_teaser = project_dir / "video" / "shorts_teaser.mp4"
            first_short = project_dir / "video" / created[0]["file"]
            if first_short.exists():
                shutil.copy2(first_short, main_teaser)

        (project_dir / "video" / "shorts_manifest.json").write_text(
            json.dumps(created, ensure_ascii=False, indent=2),
            encoding="utf-8",
        )

        self.log.info("shorts_complete", count=len(created))
        return 0.0

    def _plan_shorts_clips(
        self,
        script: Script,
        source_duration: float,
        target_duration: float,
        min_duration: float,
        max_duration: float,
        project_dir: Path | None = None,
    ) -> list[dict]:
        """Plan 1-4 Shorts (~target_duration each), adaptive to source length.

        Uses ACTUAL TTS audio durations (`audio/scene_NNN.mp3`) when available,
        since the LLM-planned `scene.duration_sec` over-estimates and composed.mp4
        is typically shorter than the script implies.

        Strategy:
        - Always: opening clip (0..target)
        - If source > target+30s: ending clip (last `target` seconds — includes sign-off)
        - If source > target*3: middle clip anchored at first 'reveal' phase scene
        - If source > target*5: extra clip anchored at first 'climax' phase scene
        Overlapping (within 20s) anchors are dropped.
        """
        # Compute actual scene start times from TTS audio
        scenes_with_time: list[tuple[Scene, float]] = []
        current_time = 0.0
        audio_dir = project_dir / "audio" if project_dir else None
        inter_scene_gap = 0.8  # matches d_tts_gen._concat_audio_with_gaps

        for i, scene in enumerate(script.scenes):
            scenes_with_time.append((scene, current_time))

            actual_dur: float | None = None
            if audio_dir is not None:
                audio_file = audio_dir / f"scene_{scene.index:03d}.mp3"
                if audio_file.exists():
                    actual_dur = self._get_duration(audio_file)

            if actual_dur and actual_dur > 0:
                current_time += actual_dur
            else:
                if scene.has_silence_before:
                    current_time += scene.silence_duration_sec
                current_time += scene.duration_sec

            if i < len(script.scenes) - 1:
                current_time += inter_scene_gap

        # Build candidate anchors (start_sec, label)
        candidates: list[tuple[float, str]] = [(0.0, "opening")]

        # Ending clip — always great because it contains the channel sign-off
        if source_duration > target_duration + 30:
            candidates.append((max(0.0, source_duration - target_duration), "ending"))

        # Middle clip anchored at reveal — only when source is long enough for ~3 distinct shorts
        if source_duration > target_duration * 3:
            for scene, start in scenes_with_time:
                if scene.phase == "reveal":
                    candidates.append((max(0.0, start - 3.0), "reveal"))
                    break

        # Extra climax clip when source is very long
        if source_duration > target_duration * 5:
            for scene, start in scenes_with_time:
                if scene.phase == "climax":
                    candidates.append((max(0.0, start - 2.0), "climax"))
                    break

        # De-duplicate anchors closer than 20s, sort by start
        candidates.sort(key=lambda x: x[0])
        deduped: list[tuple[float, str]] = []
        for start, label in candidates:
            if any(abs(start - s) < 20 for s, _ in deduped):
                continue
            deduped.append((start, label))

        # Build clips, clamp duration to source
        clips: list[dict] = []
        for start, label in deduped:
            end = min(source_duration, start + target_duration)
            duration = end - start
            if duration < min_duration:
                continue
            duration = min(max_duration, duration)
            clips.append({"start": start, "duration": duration, "label": label})

        return clips[:4]

    def _extract_short(
        self,
        source: Path,
        output: Path,
        start_sec: float,
        duration: float,
        source_duration: float,
        srt_path: Path | None,
        font_name: str,
        font_size: int,
        margin_v: int,
    ) -> None:
        """Extract a Shorts clip: 9:16 crop + scale to 1080x1920 + (optional) fresh subtitle burn."""
        if start_sec + duration > source_duration:
            duration = max(5, source_duration - start_sec)

        # Build subtitle filter as a separate chain via [in][out] labels, so the
        # commas inside force_style do not collide with the outer comma-joined chain.
        crop_scale = "crop=ih*9/16:ih,scale=1080:1920"
        if srt_path is not None and srt_path.exists():
            srt_for_ff = srt_path.resolve().as_posix()
            # libass force_style uses commas; ffmpeg's filter parser also uses commas to
            # separate filters, so backslash-escape every comma inside the style value.
            style_pairs = [
                f"FontName={font_name}",
                f"Fontsize={font_size}",
                "PrimaryColour=&H00FFFFFF",
                "OutlineColour=&H00000000",
                "BorderStyle=4",         # opaque background box
                "BackColour=&HB0000000",
                "Outline=2",
                "Shadow=0",
                f"MarginV={margin_v}",
                "Alignment=2",           # bottom-center
            ]
            style = r"\,".join(style_pairs)
            # original_size pins libass to the output resolution so Fontsize/MarginV
            # are interpreted in pixels (without it libass uses default 384x288 PlayRes
            # and everything blows up ~6.7x when scaled to 1080x1920).
            vf = f"{crop_scale},subtitles={srt_for_ff}:original_size=1080x1920:force_style={style}"
        else:
            vf = crop_scale

        subprocess.run(
            [
                "ffmpeg", "-y",
                "-ss", str(start_sec),
                "-i", str(source),
                "-t", str(duration),
                "-vf", vf,
                "-c:v", "libx264",
                "-preset", "medium",
                "-crf", "23",
                "-pix_fmt", "yuv420p",
                "-c:a", "aac",
                "-b:a", "128k",
                "-ar", "44100",
                "-ac", "2",
                "-movflags", "+faststart",
                str(output),
            ],
            capture_output=True,
            check=True,
        )

    def _slice_srt(self, src: Path, dst: Path, start_sec: float, duration_sec: float) -> None:
        """Read raw.srt, keep entries that overlap [start, start+duration], rewrite with timestamps shifted to 0."""
        end_sec = start_sec + duration_sec
        text = src.read_text(encoding="utf-8")

        ts_re = re.compile(r"(\d\d):(\d\d):(\d\d),(\d\d\d)\s+-->\s+(\d\d):(\d\d):(\d\d),(\d\d\d)")

        def to_sec(h: str, m: str, s: str, ms: str) -> float:
            return int(h) * 3600 + int(m) * 60 + int(s) + int(ms) / 1000.0

        def fmt(sec: float) -> str:
            sec = max(0.0, sec)
            h = int(sec // 3600)
            m = int((sec % 3600) // 60)
            s = int(sec % 60)
            ms = int(round((sec - int(sec)) * 1000))
            return f"{h:02d}:{m:02d}:{s:02d},{ms:03d}"

        out_blocks: list[str] = []
        idx_out = 1
        for block in re.split(r"\n\s*\n", text.strip()):
            lines = block.splitlines()
            if len(lines) < 3:
                continue
            ts_match = ts_re.search(lines[1])
            if not ts_match:
                continue
            start = to_sec(*ts_match.group(1, 2, 3, 4))
            end = to_sec(*ts_match.group(5, 6, 7, 8))

            # Keep if overlaps the window
            if end <= start_sec or start >= end_sec:
                continue
            new_start = max(0.0, start - start_sec)
            new_end = min(end - start_sec, duration_sec)
            if new_end <= new_start:
                continue

            content = "\n".join(lines[2:])
            out_blocks.append(
                f"{idx_out}\n{fmt(new_start)} --> {fmt(new_end)}\n{content}"
            )
            idx_out += 1

        dst.write_text("\n\n".join(out_blocks) + "\n", encoding="utf-8")

    def _get_duration(self, file_path: Path) -> float:
        result = subprocess.run(
            [
                "ffprobe", "-v", "error",
                "-show_entries", "format=duration",
                "-of", "default=noprint_wrappers=1:nokey=1",
                str(file_path),
            ],
            capture_output=True,
            text=True,
        )
        try:
            return float(result.stdout.strip())
        except ValueError:
            return 0.0
